version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipservices/test}
    links:
      - service
    environment:
      - GRPC_HOST=service
      - GRPC_PORT=8090

  service:
    image: pipservices/service-settings-node:latest
